### ISSUE TITLE
`make matrices` fails for GSE113197

### ISSUE THREAD

**Issue by hannes-ucsc** [DailyDreaming/load-project#119]
```
INFO:convert_matrices.py:Started conversion for `cell_files`
Writing projects/GSE113197/matrices/cell_files/matrix.mtx.body.gz.tmp ...
ERROR:convert_matrices.py:Failed to process project
Traceback (most recent call last):
  File "convert_matrices.py", line 1969, in main
    converter.convert()
  File "convert_matrices.py", line 131, in convert
    self._convert()
  File "convert_matrices.py", line 574, in _convert
    'GSM3099849_Ind7_Expression_Matrix.txt.gz'
  File "convert_matrices.py", line 179, in _convert_matrices
    input.to_mtx(input_dir=self.geo_dir, output_dir=output_dir)
  File "convert_matrices.py", line 100, in to_mtx
    cell_files_converter.convert(output_dir)
  File "/home/ubuntu/load-project.hannes/csv2mtx.py", line 79, in convert
    write_gzip_file(mtx_body_file, self)
  File "/home/ubuntu/load-project.hannes/csv2mtx.py", line 174, in write_gzip_file
    for line in lines:
  File "/home/ubuntu/load-project.hannes/csv2mtx.py", line 61, in __iter__
    if float(value):
ValueError: could not convert string to float: 'FPKM'
```

**Comment by hannes-ucsc** [comment]
PR #126
