### ISSUE TITLE
No metadata for 5016f45e-b86a-57ce-984e-a50605641d08

### ISSUE THREAD

**Issue by hannes-ucsc** [DailyDreaming/load-project#72]
make assets: 

```
Traceback (most recent call last):
  File "upload_assets.py", line 66, in <module>
    uploader.upload_files_to_bucket(options.bucket, options.directory)
  File "upload_assets.py", line 27, in upload_files_to_bucket
    with open(cs_json_path, 'r') as cs_json:
FileNotFoundError: [Errno 2] No such file or directory: 'projects/5016f45e-b86a-57ce-984e-a50605641d08/bundle/donor_organism_0.json'
Makefile:29: recipe for target 'assets' failed
```

**Comment by hannes-ucsc** [comment]
There may be more projects like this.

**Comment by DailyDreaming** [comment]
@hannes-ucsc That `uuid` does not appear when I generate metadata locally.

**Comment by DailyDreaming** [comment]
@hannes-ucsc Not sure where that accession and uuid came from but `GSE94820` isn't any of the excel files (or contained in any of the fields of those files).

**Comment by DailyDreaming** [comment]
@hannes-ucsc I count 82 geo projects in the `/projects` folder.  There are only 77 excel inputs though.

**Comment by hannes-ucsc** [comment]
Closing in favour of #118
